{"error": null, "issues": [{"address": 304, "code": "function Command(address adr,bytes data)\n    payable\n    public\n    {\n        require(msg.sender == Owner);\n        // <yes> <report> UNCHECKED_LL_CALLS\n        adr.call.value(msg.value)(data);\n    }", "debug": "calldata_WhaleGiveaway1_32 + 4: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc\ncalldata_WhaleGiveaway1_0: 0xba21d62a00000000000000000000000000000000000000000000000000000000\ncalldatasize_WhaleGiveaway1: 0x4\n", "description": "A possible integer overflow exists in the function `Command(address,bytes)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "Command(address,bytes)", "lineno": 39, "title": "Integer Overflow ", "type": "Warning"}, {"address": 737, "code": "Owner.transfer(this.balance)", "debug": "", "description": "A possible transaction order independence vulnerability exists in function withdraw(). The value or direction of the call statement is determined from a tainted storage location", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "withdraw()", "lineno": 36, "title": "Transaction order dependence", "type": "Warning"}, {"address": 1034, "code": "adr.call.value(msg.value)(data)", "debug": "", "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "Command(address,bytes)", "lineno": 45, "title": "Message call to external contract", "type": "Warning"}, {"address": 1034, "code": "adr.call.value(msg.value)(data)", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "Command(address,bytes)", "lineno": 45, "title": "Unchecked CALL return value", "type": "Informational"}, {"address": 1164, "code": "Owner.transfer(this.balance)", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 1258\n", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "redeem()", "lineno": 26, "title": "Multiple Calls", "type": "Information"}, {"address": 1164, "code": "Owner.transfer(this.balance)", "debug": "", "description": "A possible transaction order independence vulnerability exists in function redeem(). The value or direction of the call statement is determined from a tainted storage location", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "redeem()", "lineno": 26, "title": "Transaction order dependence", "type": "Warning"}, {"address": 1258, "code": "msg.sender.transfer(this.balance)", "debug": "SOLVER OUTPUT:\nretval_1164: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncallvalue: 0xddd2a1dd7429000\ncalldata_WhaleGiveaway1_0: 0xbe040fb000000000000000000000000000000000000000000000000000000000\ncalldatasize_WhaleGiveaway1: 0x4\n", "description": "In the function `redeem()` a non-zero amount of Ether is sent to msg.sender.\nIt seems that this function can be called without restrictions.", "filename": "/data/0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol", "function": "redeem()", "lineno": 27, "title": "Ether send", "type": "Warning"}], "success": true}