{
    "errors": [],
    "fails": [],
    "findings": [
        {
            "column": "18",
            "column_end": "49",
            "filename": "dataset/reentrancy/simple_dao.sol",
            "line": "19",
            "line_end": "19",
            "name": "Missing Check of Return Value from external Call"
        },
        {
            "column": "18",
            "column_end": "49",
            "filename": "dataset/reentrancy/simple_dao.sol",
            "line": "19",
            "line_end": "19",
            "name": "Reentrancy Vulnerability"
        },
        {
            "column": "5",
            "column_end": "30",
            "filename": "dataset/reentrancy/simple_dao.sol",
            "line": "13",
            "line_end": "13",
            "name": "Result of expression can be over- or under-flown by external entity"
        }
    ],
    "infos": [],
    "parser": {
        "id": "ccc",
        "mode": "solidity",
        "version": ""
    }
}
