====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m................[92m ESTABLISHED [0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8550): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maian.py", line 183, in <module>
    main(sys.argv[1:])
  File "maian.py", line 119, in main
    if args.soliditycode:   contract_address = deploy_contract(args.soliditycode[1], MyGlobals.etherbase_account)
  File "/MAIAN/tool/contracts.py", line 84, in deploy_contract
    MyGlobals.web3.geth.personal.unlock_account(etherbase, '1', 15000)
  File "/usr/local/lib/python3.8/dist-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/usr/local/lib/python3.8/dist-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8550): Read timed out. (read timeout=10)
[1m[ ] Deploying contract [0m
====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m..[92m ESTABLISHED [0m
[1m[ ] Sending Ether to contract 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306  [0m... tx[0] mined [92m Sent! [0m
[1m[ ] Deploying contract [0m[92m confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306 [0m
[1m[ ] Contract code length on the blockchain : [0m [92m  1212  : 0x6080604052600436106100625760... [0m
[1m[ ] Contract address saved in file: [0m[92m./out/ETH_FUND.address [0m
[1m[ ] The contract balance: 44  [0m[92m Positive balance[0m
[94m[ ] Check if contract is PRODIGAL[0m

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 608060405260043610610062576000357c0100000000000000...
[ ] Bytecode length    : 2424
[ ] Blockchain contract: True
[ ] Debug              : False

[ ][1m Search with call depth: 1   : [0m111111
[ ][1m Search with call depth: 2   : [0m1122222212222212222212222221
[ ][1m Search with call depth: 3   : [0m112223333323333322122223333321222233333212222221
[92m[+] No prodigal vulnerability found [0m

====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m..[92m ESTABLISHED [0m
[1m[ ] Deploying contract [0m[92m confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306 [0m
[1m[ ] Contract code length on the blockchain : [0m [92m  1212  : 0x6080604052600436106100625760... [0m
[1m[ ] Contract address saved in file: [0m[92m./out/ETH_FUND.address [0m
[94m[ ] Check if contract is GREEDY[0m

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 608060405260043610610062576000357c0100000000000000...
[ ] Bytecode length    : 2424
[ ] Debug              : False
[92m[+][0m [1mContract can receive Ether[0m

[ ][1m Search with call depth: 1   : [0m1
[92m[+] No locking vulnerability found [0m

====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m..[92m ESTABLISHED [0m
[1m[ ] Deploying contract [0m[92m confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306 [0m
[1m[ ] Contract code length on the blockchain : [0m [92m  1381  : 0x60806040526004361061004c5760... [0m
[1m[ ] Contract address saved in file: [0m[92m./out/Log.address [0m
[94m[ ] Check if contract is SUICIDAL[0m

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 60806040526004361061004c576000357c0100000000000000...
[ ] Bytecode length    : 2762
[ ] Blockchain contract: True
[ ] Debug              : False

[92m[-] The code does not contain SUICIDE instructions, hence it is not vulnerable[0m

====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m..[92m ESTABLISHED [0m
[1m[ ] Sending Ether to contract 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306  [0m........ tx[0] mined [92m Sent! [0m
[1m[ ] Deploying contract [0m[92m confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306 [0m
[1m[ ] Contract code length on the blockchain : [0m [92m  1381  : 0x60806040526004361061004c5760... [0m
[1m[ ] Contract address saved in file: [0m[92m./out/Log.address [0m
[1m[ ] The contract balance: 44  [0m[92m Positive balance[0m
[94m[ ] Check if contract is PRODIGAL[0m

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 60806040526004361061004c576000357c0100000000000000...
[ ] Bytecode length    : 2762
[ ] Blockchain contract: True
[ ] Debug              : False
[92m[+] The code does not have CALL/SUICIDE, hence it is not prodigal[0m

====================================================================================================
[1m[ ] Compiling Solidity contract from the file /data/0x941d225236464a25eb18076df7da6a91d0f95e9e.sol ... [0m[92m Done [0m
[1m[ ] Connecting to PRIVATE blockchain emptychain  [0m..[92m ESTABLISHED [0m
[1m[ ] Deploying contract [0m[92m confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306 [0m
[1m[ ] Contract code length on the blockchain : [0m [92m  1381  : 0x60806040526004361061004c5760... [0m
[1m[ ] Contract address saved in file: [0m[92m./out/Log.address [0m
[94m[ ] Check if contract is GREEDY[0m

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 60806040526004361061004c576000357c0100000000000000...
[ ] Bytecode length    : 2762
[ ] Debug              : False
[91m[-][0m [1mContract can receive Ether[0m

[92m[-] No lock vulnerability found because the contract cannot receive Ether [0m